# Generated by Django 2.2.7 on 2019-11-19 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20191119_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='master_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lock',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
