# Generated by Django 2.2.7 on 2019-11-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191119_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='expired',
        ),
        migrations.AlterField(
            model_name='code',
            name='expiry_time',
            field=models.DateTimeField(null=True),
        ),
    ]
